config/routes.rb
Rails.application.routes.draw do
  resources :labour_accounts
  resources :customer_accounts
  resources :farmer_accounts
  resources :sales_and_deaths
  resources :month_on_weights
  resources :feed_availabilities
  resources :pending_works
  resources :loads
  resources :coconut_invoices
  resources :coconut_expenses
  resources :customers
  resources :vechicles
  resources :mattais
  resources :kopparais
  resources :salaries
  resources :farmer_bills
  resources :purchaser_bills
  resources :purchasers
  resources :farmer_lands
  resources :farmers
  resources :labours
  resources :places
	
 
    devise_for :users
    default_url_options :host => "goatfarm.com"

    resources :farm_expenses
	#Routes For Cow
	root to: 'home#main_page'
	resources :cows, only: [:new, :create, :edit, :update, :index]
	resources :calves, only: [:new, :create, :edit, :update, :index]
	resources :feed_rates, only: [:new, :create, :edit, :update]
	resources :feeds, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :milk_productions, only: [:index, :new, :create, :edit, :update]
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'home' => 'home#main_page'
	get 'cow_health' => 'cows#cow_health'
	post 'cow_health' => 'cows#create_health'
	get 'history' => 'milk_productions#history_cow', as: 'history'
	get 'milk_account' => 'milk_productions#today'
	get 'health' => 'cows#health'
	post 'date_account' => 'milk_productions#today'

	#Routes For Goat
	resources :goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :diseases, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :mate_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :parent_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	get 'goat_status' => 'goats#goat_status'
	post 'goat_status' => 'goats#create_status'
	get 'goat_insurance' => 'goats#goat_insurance'
	post 'goat_insurance' => 'goats#create_insurance'
	get 'farm_status' => 'goats#farm_status'
	get 'find_goat' => 'goats#find_goat'
	get 'goat_diseases' => 'diseases#goat_diseases'
	get 'goat_disease' => 'diseases#goat_disease'
	post 'goat_disease' => 'diseases#create_goat_disease'
	get 'goat_disease/:id/edit', to: 'diseases#edit_goat_disease', as: 'edit_goat_disease'
	post 'update_goat_disease' => 'diseases#update_goat_disease'
	get 'goat_death' => 'diseases#goat_death'
	post 'goat_death' => 'diseases#create_goat_death'
	resources :main_works, only: [:index, :new, :create, :edit, :update, :destroy]
	resources :daily_works, only: [:index, :new, :create, :edit, :update, :destroy]
	get 'good_morning' => 'daily_works#good_morning'
	post 'date_work' => 'daily_works#date_work'
	get 'date_work' => 'daily_works#date_work'
    get 'invoice_year' => 'invoices#invoice_year'
	resources :invoices, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :rack_details, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :batches, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :goat_weights, only: [:new, :create, :edit, :update, :index, :destroy ]
	get  'batch_weight' => 'goat_weights#batch_weight'
	post  'create_batch_weight' => 'goat_weights#create_batch_weight'
	post  'year_income' => 'home#year_income'
	resources :lands, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crops, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :waters, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :fertilizers, only: [:new, :create, :edit, :update, :index, :show ] 
	get  'land_water' => 'waters#land_water'
	post 'land_water_create' => 'waters#land_water_create'
	get  'land_crop' => 'crops#land_crop'
	post 'land_crop_create' => 'crops#land_crop_create'	
	get 'fodder_management' => 'lands#fodder_management'	
	resources :dry_fodders, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crop_activities, only: [:new, :create, :edit, :update, :index, :show ] 
	get 'goat_data' => 'goats#get_goat_data'
	get 'get_hole_goat_data' => 'goats#get_hole_goat_data'
	get 'goat_kid_data' => 'goats#goat_kid_data'
	get 'kid_weight_data' => 'goats#kid_weight_data'
	get 'goat_data_batch_wise' => 'batches#goat_data_batch_wise'
	get 'goat_pending_work' => 'pending_works#goat_pending_work'
	get 'daily_pending_work' => 'pending_works#daily_pending_work'

	# Coconut business routes start
	resources :places
	resources :labours
	resources :farmers
	resources :farmer_lands
	resources :vechicles
	resources :purchasers
	resources :purchaser_bills
	resources :farmer_bills
	resources :salarys
	resources :loads
	resources :coconut_invoices
	resources :kopparais
	resources :mattais
	resources :expensess
	get 'find_farmer' => 'farmers#find_farmer'
	post 'tally_farmer' => 'farmers#tally_farmer'
	post 'tally_customer' => 'farmers#tally_customer'
	post 'tally_labour' => 'farmers#tally_labour'
	post 'update_pay' => 'farmers#update_pay'
	
	# Coconut business routes ends
	
	# pdf generation
	get 'download_form' => 'milk_productions#download_form'
	# post 'download_data' => 'milk_productions#download_data'
	post 'download_data', to: 'milk_productions#download_data', as: 'download_data'
	get 'today_farm_update' => 'milk_productions#today_farm_update'
	post 'create_today_farm_status' => 'milk_productions#create_today_farm_status'
	get 'today_work', to: 'milk_productions#generate_pdf', as: 'generate_pdf'
	resources :feed_consumptions
	
end

app/models/crop.rb
class Crop < ApplicationRecord
	has_many :land_crops, inverse_of: :crop
	
	validates_presence_of :name
	validates_presence_of :yield
	validates_presence_of :details
	validates_presence_of :intercrop
	validates_presence_of :nutrition
	enum variety: {'Monocot':1, 'Dicot': 2 }
	enum period: {'40':1, '45':2, '50':3, '60':4, '80':5, '90':6, '120':7, '130':8, '180':9, '1':10, '2':11, '3':12, '4':13, '5':14 }
	enum seed_acre: {  '1Kg':1, '2Kg':2, '3Kg':3, '4Kg':4, '5Kg':5, '6Kg':6, '7Kg':7, '8Kg':8, '9Kg':9, '10Kg':10, '11Kg':11, '12Kg':12, '13Kg':13, '14Kg':14, '15Kg':15, '16Kg':16, '17Kg':17, '18Kg':18, '19Kg':19, '20Kg':20, '21Kg':21, '22Kg':22, '23Kg':23, '24Kg':24, '25Kg':25, '26Kg':26, '27Kg':27, '28Kg':28, '29Kg':29, '30Kg':30,  '31Kg':31, '32Kg':32, '33Kg':33, '34Kg':34, '35Kg':35, '36Kg':36, '37Kg':37, '38Kg':38, '39Kg':39, '40Kg':40,'41Kg':41, '42Kg':42, '43Kg':43, '44Kg':44, '45Kg':45, '46Kg':46, '47Kg':47, '48Kg':48, '49Kg':49, '50Kg':50  }
	enum water_requirement: { 'High':1, 'Medium':2, 'Low':3}
	enum sowing_distance: { '1 ft':1, '1.5 ft':2, '2 ft':3, '2.5 ft':4, '3 ft':5,'3.5 ft':6,  '4 ft':7, '4.5 ft':8, '5 ft':9, '5.5 ft':10, '6 ft':11, '6.5 ft':12, '7 ft':13, '7.5 ft':14, '8 ft':15, '8.5': 16}
	enum season: {'January':1, 'February':2, 'March':3, 'April':4, 'May':5, 'June':6, 'July':7, 'August':8, 'September':9, 'October':10, 'November':11, 'December':12}
end

app/controllers/crops_controller.rb
class CropsController < BaseController

	def index
		@crop = Crop.all
	end

	def new
		@crop = Crop.new
	end

	def create
		crop = Crop.create(crop_params)
		respond_to do |format|
		  	if crop.save 
		  	 format.html {redirect_to crops_url, flash: { success: 'Crop Created Successfully' }}
		  	 format.json { render json: {message: 'Crop Created Successfully'}, status: :created }
		  	else
		  	 format.html { redirect_to crops_url, flash: { errors: crop.errors.full_messages.to_sentence} }
			format.json { render json: {errors: crop.errors.full_messages.to_sentence}, status: :unprocessable_entity }
			end
		end
	end

	def edit
		@crop = Crop.find(params[:id])
	end
	def show
		@crop = Crop.find(params[:id])
	end

	def update
		crop = Crop.find(params[:id])
	 	respond_to do |format|
			if crop.update(crop_params)
			# crop.update(:goat_sales_attributes => [:goat_id, :weight, :amount])
			format.html {redirect_to crops_url, flash: { success: 'Crop Updated Successfully' } }
			format.json { render json: {message: 'Crop Updated Successfully'}, status: :created }
			else
			format.html { redirect_to edit_crop_path(id: params[:id]) , flash: { errors: crop.errors.full_messages.to_sentence} }
			format.json { render json: {errors: crop.errors.full_messages.to_sentence}, status: :unprocessable_entity }
			end
		end
	end

	def land_crop
		@land_crop = LandCrop.new
		@land_crops = LandCrop.all.order(:status)
	end

	def land_crop_create
		land_crop = LandCrop.create(land_crop_params)
		respond_to do |format|
		  	if land_crop.save
		  	 format.html {redirect_to land_crop_url, flash: { success: 'Land Connected With Crop' }}
		  	 format.json { render json: {message: 'Land Connected With Crop'}, status: :created }
		  	else
		  	 format.html { redirect_to land_crop_url, flash: { errors: land_crop.errors.full_messages.to_sentence} }
			format.json { render json: {errors: land_crop.errors.full_messages.to_sentence}, status: :unprocessable_entity }
			end
		end
	end


	private
	def crop_params
		params.require(:crop).permit(:name, :details, :yield, :varieties , :nutrition, :period, :seed_acre, :intercrop, :water_requirement, :sowing_distance, :season, :business_id)
	end
	def land_crop_params
		params.require(:land_crop).permit(:land_id, :crop_id, :date,:fodder, :status, :business_id)
	end

end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_form.html.erb
<%= form_for (@crop) do |f| %>
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block" > 
             <%= image_tag("our_boer.jpg", :class => 'bg-register-image', :size => "450x360"  ) %>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Crop</h1>
              </div>
              <form class="user">
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Name :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_field :name, class: 'input form-control form-control-user', placeholder: 'Enter Name  ', id: 'name', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Yield Ton/Acre :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_field :yield, class: 'input form-control form-control-user', placeholder: 'Enter Yield Ton/Acre  ', id: 'yield', required: true %>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Variety :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :variety, Crop.varieties.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Nutrition :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_area :nutrition, class: 'input form-control form-control-user', placeholder: 'Enter Nutrition   ', id: 'nutrition', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Period/Days:</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :period, Crop.periods.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Seed Per/Acre :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :seed_acre, Crop.seed_acres.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Intercrop :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_field :intercrop, class: 'input form-control form-control-user', placeholder: 'Enter Intercrop Ton/Acre  ', id: 'intercrop', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Water Requirement :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :water_requirement, Crop.water_requirements.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Sowing Distance :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :sowing_distance, Crop.sowing_distances.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Season :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :season, Crop.seasons.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Details :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_area  :details, class: 'input form-control form-control-user', placeholder: 'Enter Details  ', id: 'cent', required: true %>
                  </div>
                </div>
                 <%= f.hidden_field :business_id, value: UserEmployee.find_by(employee_id: current_user).business.id %>
                <div class="field has-text-centered">
                  <button type="submit" class="btn btn-facebook btn-user btn-block">Submit</button>
                </div>
                <hr>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/crops/edit.html.erb
<%= render :partial => 'form' %>

app/views/crops/index.html.erb
<div class="container-fluid">

	<div class="container-fluid">
  <!-- Page Heading -->
    <div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: right;"> <%= link_to 'Fodder Data', fodder_management_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-warning" style="float: right;"> <%= link_to 'Land Crop Activities', crop_activities_path %></div>
  	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-warning" style="float: right;"> <%= link_to 'Land Water', land_water_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-warning" style="float: right;"> <%= link_to 'Land Crop', land_crop_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: left;"> <%= link_to 'Add Crop', new_crop_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: left;"> <%= link_to 'Fertilizer', fertilizers_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: left;"> <%= link_to 'Dry Fodder', dry_fodders_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: left;"> <%= link_to 'Land', lands_path %></div>
	<div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success" style="float: left;"> <%= link_to 'Water', waters_path %></div>

  <!-- Page Heading -->
	<br />
	<br />
  	<h1 class="h3 mb-2 text-gray-800">Our Crop</h1>
	<% if @crop.exists? %>
		<div class="card shadow mb-4">
			<div class="card-body">
			  <div class="table-responsive">
			    <table class="table table-bordered" width="100%" cellspacing="0">
			        <thead>
			          <tr>
			            <th>Name</th>
			            <th>Yield Ton/Acre</th>
			            <th>Nutrition</th>
			            <th>Seed/Acre</th>
			            <th>Intercrop</th>
			            <th>Season</th>
			            <th>Water Requirement</th>
			            <th>Sowing</th>
			            <th>Season</th>
			            <th>Details</th>
			            <th>Edit</th>
			        </thead>
			        <% @crop.each do |crop| %>
			        <tbody>
			          <tr>
			            <td><%= crop.name %></td>
			            <td><%= crop.yield %></td>
			            <th><%= crop.nutrition %></th>
						<th><%= crop.period %></th>
						<th><%= crop.seed_acre %></th>
						<th><%= crop.intercrop %></th>
						<th><%= crop.water_requirement %></th>
						<th><%= crop.sowing_distance %></th>
						<th><%= crop.season %></th>
			            <td><%= crop.details %></td>
			            <td><div class="text-xs font-weight-bold text-uppercase mb-3 btn btn-outline-success"> <%= link_to 'Edit crop', edit_crop_path(id: crop.id) %></div></td>
			          </tr>
			        </tbody>
			       <% end %>
			    </table>
			  </div>
			</div>
		</div>
	<% end %>
 	</div>
</div>

app/views/crops/land_crop.html.erb
<%= form_for @land_crop, url: land_crop_create_path, html: { method: :post } do |f| %>
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block" > 
             <%= image_tag("our_boer.jpg", :class => 'bg-register-image', :size => "450x360"  ) %>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Connect Land With Crop</h1>
              </div>
              <form class="user">
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Land :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :land_id, options_for_select(Land.all.collect {|u| [u.name, u.id]}, :selected => f.object.land_id), class: 'form-control form-control-user',prompt: "Select Land", required: 'true' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Water :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :crop_id, options_for_select(Crop.all.collect {|u| [u.name, u.id]},:selected => f.object.crop_id), class: 'form-control form-control-user',prompt: "Select Land", required: 'true' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Fodder :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :fodder, LandCrop.fodders.keys, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Date :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.date_field :date, class: 'input input form-control form-control-user',id: 'date', placeholder: 'Enter Date', required: true %>
                  </div>
                </div>
                <%= f.hidden_field :business_id, value: UserEmployee.find_by(employee_id: current_user).business.id %>
                <div class="field has-text-centered">
                  <button type="submit" class="btn btn-facebook btn-user btn-block">Submit</button>
                </div>
                <hr>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="container-fluid">

  <!-- Page Heading -->
  <div class="container-fluid">
  <br />
  <br />
  <h1 class="h3 mb-2 text-gray-800">Land Crop</h1>
  <% if @land_crops.exists? %>
    <div class="card shadow mb-4">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Land</th>
                  <th>Crop</th>
                  <th>Fodder</th>
                  <th>Date</th>
                  <th>Live Day</th>
                  <th>Status</th>
                </tr>
              </thead>
              <% @land_crops.each do |crop| %>
              <tbody>
                <tr>
                  <td><%= crop.land.name %></td>
                  <td><%= crop.crop.name %></td>
                  <td><%= crop.fodder if crop.fodder.present? %>  </td>
                  <td><%= crop.date %></td> 
                  <td><%= (Date.today - crop.date).to_i %></td>
                  <td><%= crop.status %></td>
                </tr>
              </tbody>
             <% end %>
          </table>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/crops/new.html.erb
<%= render :partial => 'form' %>