config/routes.rb
Rails.application.routes.draw do
  resources :labour_accounts
  resources :customer_accounts
  resources :farmer_accounts
  resources :sales_and_deaths
  resources :month_on_weights
  resources :feed_availabilities
  resources :pending_works
  resources :loads
  resources :coconut_invoices
  resources :coconut_expenses
  resources :customers
  resources :vechicles
  resources :mattais
  resources :kopparais
  resources :salaries
  resources :farmer_bills
  resources :purchaser_bills
  resources :purchasers
  resources :farmer_lands
  resources :farmers
  resources :labours
  resources :places
	
 
    devise_for :users
    default_url_options :host => "goatfarm.com"

    resources :farm_expenses
	#Routes For Cow
	root to: 'home#main_page'
	resources :cows, only: [:new, :create, :edit, :update, :index]
	resources :calves, only: [:new, :create, :edit, :update, :index]
	resources :feed_rates, only: [:new, :create, :edit, :update]
	resources :feeds, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :milk_productions, only: [:index, :new, :create, :edit, :update]
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'home' => 'home#main_page'
	get 'cow_health' => 'cows#cow_health'
	post 'cow_health' => 'cows#create_health'
	get 'history' => 'milk_productions#history_cow', as: 'history'
	get 'milk_account' => 'milk_productions#today'
	get 'health' => 'cows#health'
	post 'date_account' => 'milk_productions#today'

	#Routes For Goat
	resources :goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :diseases, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :mate_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :parent_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	get 'goat_status' => 'goats#goat_status'
	post 'goat_status' => 'goats#create_status'
	get 'goat_insurance' => 'goats#goat_insurance'
	post 'goat_insurance' => 'goats#create_insurance'
	get 'farm_status' => 'goats#farm_status'
	get 'find_goat' => 'goats#find_goat'
	get 'goat_diseases' => 'diseases#goat_diseases'
	get 'goat_disease' => 'diseases#goat_disease'
	post 'goat_disease' => 'diseases#create_goat_disease'
	get 'goat_disease/:id/edit', to: 'diseases#edit_goat_disease', as: 'edit_goat_disease'
	post 'update_goat_disease' => 'diseases#update_goat_disease'
	get 'goat_death' => 'diseases#goat_death'
	post 'goat_death' => 'diseases#create_goat_death'
	resources :main_works, only: [:index, :new, :create, :edit, :update, :destroy]
	resources :daily_works, only: [:index, :new, :create, :edit, :update, :destroy]
	get 'good_morning' => 'daily_works#good_morning'
	post 'date_work' => 'daily_works#date_work'
	get 'date_work' => 'daily_works#date_work'
    get 'invoice_year' => 'invoices#invoice_year'
	resources :invoices, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :rack_details, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :batches, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :goat_weights, only: [:new, :create, :edit, :update, :index, :destroy ]
	get  'batch_weight' => 'goat_weights#batch_weight'
	post  'create_batch_weight' => 'goat_weights#create_batch_weight'
	post  'year_income' => 'home#year_income'
	resources :lands, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crops, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :waters, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :fertilizers, only: [:new, :create, :edit, :update, :index, :show ] 
	get  'land_water' => 'waters#land_water'
	post 'land_water_create' => 'waters#land_water_create'
	get  'land_crop' => 'crops#land_crop'
	post 'land_crop_create' => 'crops#land_crop_create'	
	get 'fodder_management' => 'lands#fodder_management'	
	resources :dry_fodders, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crop_activities, only: [:new, :create, :edit, :update, :index, :show ] 
	get 'goat_data' => 'goats#get_goat_data'
	get 'get_hole_goat_data' => 'goats#get_hole_goat_data'
	get 'goat_kid_data' => 'goats#goat_kid_data'
	get 'kid_weight_data' => 'goats#kid_weight_data'
	get 'goat_data_batch_wise' => 'batches#goat_data_batch_wise'
	get 'goat_pending_work' => 'pending_works#goat_pending_work'
	get 'daily_pending_work' => 'pending_works#daily_pending_work'

	# Coconut business routes start
	resources :places
	resources :labours
	resources :farmers
	resources :farmer_lands
	resources :vechicles
	resources :purchasers
	resources :purchaser_bills
	resources :farmer_bills
	resources :salarys
	resources :loads
	resources :coconut_invoices
	resources :kopparais
	resources :mattais
	resources :expensess
	get 'find_farmer' => 'farmers#find_farmer'
	post 'tally_farmer' => 'farmers#tally_farmer'
	post 'tally_customer' => 'farmers#tally_customer'
	post 'tally_labour' => 'farmers#tally_labour'
	post 'update_pay' => 'farmers#update_pay'
	
	# Coconut business routes ends
	
	# pdf generation
	get 'download_form' => 'milk_productions#download_form'
	# post 'download_data' => 'milk_productions#download_data'
	post 'download_data', to: 'milk_productions#download_data', as: 'download_data'
	get 'today_farm_update' => 'milk_productions#today_farm_update'
	post 'create_today_farm_status' => 'milk_productions#create_today_farm_status'
	get 'today_work', to: 'milk_productions#generate_pdf', as: 'generate_pdf'
	resources :feed_consumptions
	
end

app/models/pending_work.rb
class PendingWork < ApplicationRecord
  belongs_to :user, inverse_of: :pending_works
  belongs_to :business, inverse_of: :pending_works

  enum work_type: { 'Immediate': 1, 'Daily': 2, 'Goat': 3}
end

app/controllers/pending_works_controller.rb
class PendingWorksController < ApplicationController
  before_action :set_pending_work, only: %i[ show edit update destroy ]

  # GET /pending_works or /pending_works.json
  def index
    @pending_works = PendingWork.where(business_id: 1, status: false, work_type: "Immediate").order(updated_at: :desc)
  end

  def goat_pending_work
    @pending_works = PendingWork.where(business_id: 1, status: false, work_type: "Goat").order(updated_at: :desc)
  end

  def daily_pending_work
    @pending_works = PendingWork.where(business_id: 1, status: false, work_type: "Daily").order(date: :ASC)
  end

  # GET /pending_works/1 or /pending_works/1.json
  def show
  end

  # GET /pending_works/new
  def new
    @pending_work = PendingWork.new
  end

  # GET /pending_works/1/edit
  def edit
  end

  # POST /pending_works or /pending_works.json
  def create
    @pending_work = PendingWork.new(pending_work_params)

    respond_to do |format|
      if @pending_work.save
        format.html { redirect_to pending_work_url(@pending_work), notice: "Pending work was successfully created." }
        format.json { render :show, status: :created, location: @pending_work }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pending_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pending_works/1 or /pending_works/1.json
  def update
    respond_to do |format|
      if @pending_work.update(pending_work_params)
        format.html { redirect_to pending_work_url(@pending_work), notice: "Pending work was successfully updated." }
        format.json { render :show, status: :ok, location: @pending_work }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pending_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pending_works/1 or /pending_works/1.json
  def destroy
    @pending_work.destroy

    respond_to do |format|
      format.html { redirect_to pending_works_url, notice: "Pending work was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pending_work
      @pending_work = PendingWork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pending_work_params
      params.require(:pending_work).permit(:work, :work_type, :date, :status, :user_id, :business_id)
    end
end

app/helpers/pending_works_helper.rb
module PendingWorksHelper
end

app/views/pending_works/_form.html.erb
<%= form_for @pending_work do |f| %>
  <div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block"> 
            <%= image_tag("coconut.jpg", class: 'bg-register-image', size: "450x360") %>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Kopparai</h1>
              </div>
              <%= f.fields_for :pending_work do |place_fields| %>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Date :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="field">
                      <%= f.date_field :date, class: 'input input form-control form-control-user',id: 'date', placeholder: 'Enter Date', required: true %>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Work :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_field :work, class: 'input form-control form-control-user', placeholder: 'Enter Work', id: 'kg', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Action :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :work_type, PendingWork.work_types.keys, class: 'form-control'%>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="is_active" class="label">Is Active :</label>
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <label class="radio-inline"><%= f.radio_button :status, true, checked: true %> Yes</label>
                    <label class="radio-inline"><%= f.radio_button :status, false %> No</label>
                  </div>
                </div>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :business_id, value: UserEmployee.find_by(employee_id: current_user).business.id %>
              <% end %>
              <div class="field has-text-centered">
                <button type="submit" class="btn btn-facebook btn-user btn-block">Submit</button>
              </div>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pending_works/daily_pending_work.html.erb
<div class="container-fluid">

 <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <%= link_to 'New pending work', new_pending_work_path, class: 'btn btn-primary mb-3' %>
  </div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Immediate Work', pending_works_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Goat Work',  goat_pending_work_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Daily Work', daily_pending_work_path %></div>
  </div>
  <br />
  <div class="container-fluid">
    
    <h1 class="h3 mb-2 text-gray-800">Daily Work</h1>
    <br />
    <!-- DataTales Example -->
    <% if @pending_works.exists? %>
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Work</th>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Edit</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  <% @pending_works.each do |pending_work| %>
                  <tr>
                  <td><%= pending_work.work %></td>
                  <td><%= pending_work.date.strftime("%Y-%m-%d") %></td>
                  <td><%= pending_work.work_type %></td>
                  <td><%= pending_work.status %></td>
                  <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Edit Work', edit_pending_work_path(pending_work) %></div></td>
                  <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-warning"> <%= link_to 'Delete', pending_work, :method => :delete, data: { confirm: "Really?" } %></div></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pending_works/edit.html.erb
<h1>Editing pending work</h1>

<%= render "form", pending_work: @pending_work %>

<br>

<div>
  <%= link_to "Show this pending work", @pending_work %> |
  <%= link_to "Back to pending works", pending_works_path %>
</div>

app/views/pending_works/goat_pending_work.html.erb
<div class="container-fluid">

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <%= link_to 'New pending work', new_pending_work_path, class: 'btn btn-primary mb-3' %>
  </div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Immediate Work', pending_works_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Goat Work',  goat_pending_work_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Daily Work', daily_pending_work_path %></div>
  </div>
  <br />
  <div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Goat Work</h1>
    <br />
    <!-- DataTales Example -->
    <% if @pending_works.exists? %>
        <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                    <th>Work</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Edit</th>
                    <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <% @pending_works.each do |pending_work| %>
                    <tr>
                    <td><%= pending_work.work %></td>
                    <td><%= pending_work.work_type %></td>
                    <td><%= pending_work.status %></td>
                    <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Edit Work', edit_pending_work_path(pending_work) %></div></td>
                    <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-warning"> <%= link_to 'Delete', pending_work, :method => :delete, data: { confirm: "Really?" } %></div></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
            </div>
        </div>
        </div>
    <% end %>
  </div>
</div>

app/views/pending_works/index.html.erb
<div class="container-fluid">

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <%= link_to 'Add pending work', new_pending_work_path, class: 'btn btn-primary mb-3' %>
  </div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Immediate Work', pending_works_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-0 btn btn-outline-success"> <%= link_to 'Goat Work',  goat_pending_work_path %></div>
    <div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Daily Work', daily_pending_work_path %></div>
  </div>
  <br />
  <div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Immediate Work</h1>
    <br />
    <!-- DataTales Example -->
    <% if @pending_works.exists? %>
      <div class="card shadow mb-4">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Work</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Edit</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  <% @pending_works.each do |pending_work| %>
                  <tr>
                  <td><%= pending_work.work %></td>
                  <td><%= pending_work.work_type %></td>
                  <td><%= pending_work.status %></td>
                  <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'Edit Work', edit_pending_work_path(pending_work) %></div></td>
                  <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-warning"> <%= link_to 'Delete', pending_work, :method => :delete, data: { confirm: "Really?" } %></div></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pending_works/new.html.erb
<h1>New pending work</h1>

<%= render "form", pending_work: @pending_work %>

<br>

<div>
  <%= link_to "Back to pending works", pending_works_path %>
</div>

app/views/pending_works/show.html.erb
<div class="container-fluid">
  <div class="container-fluid">
    <div class="row justify-content-end">
      <div class="col-auto">
        <%= link_to 'Back to PendingWorks', pending_works_path, class: 'btn btn-primary mb-3' %>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">PendingWork</h1>
	<br />
	<% if @pending_work.present? %>
		<div class="card shadow mb-3">
			<div class="card-body">
				<div class="table-responsive">
			    <table class="table table-bordered" width="100%" cellspacing="0">
			        <thead>
			          <tr>
			          	<th>Work</th>
                  <th>Type</th>
                  <th>Date</th>
                  <th>Status</th>
			          </tr>
			        </thead>
			        <tbody>
			          <tr>
			            <td><%= @pending_work.work %></td>
                  <td><%= @pending_work.work_type %></td>
                  <td><%= @pending_work.date.in_time_zone('Kolkata').strftime("%Y-%m-%d %H:%M ")%></td>
                  <td><%= @pending_work.status%></td>
			          </tr>
			        </tbody>
			    </table>
			   </div>
			</div>
		</div>
	<% end %>
</div>