config/routes.rb
Rails.application.routes.draw do
  resources :labour_accounts
  resources :customer_accounts
  resources :farmer_accounts
  resources :sales_and_deaths
  resources :month_on_weights
  resources :feed_availabilities
  resources :pending_works
  resources :loads
  resources :coconut_invoices
  resources :coconut_expenses
  resources :customers
  resources :vechicles
  resources :mattais
  resources :kopparais
  resources :salaries
  resources :farmer_bills
  resources :purchaser_bills
  resources :purchasers
  resources :farmer_lands
  resources :farmers
  resources :labours
  resources :places
	
 
    devise_for :users
    default_url_options :host => "goatfarm.com"

    resources :farm_expenses
	#Routes For Cow
	root to: 'home#main_page'
	resources :cows, only: [:new, :create, :edit, :update, :index]
	resources :calves, only: [:new, :create, :edit, :update, :index]
	resources :feed_rates, only: [:new, :create, :edit, :update]
	resources :feeds, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :milk_productions, only: [:index, :new, :create, :edit, :update]
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get 'home' => 'home#main_page'
	get 'cow_health' => 'cows#cow_health'
	post 'cow_health' => 'cows#create_health'
	get 'history' => 'milk_productions#history_cow', as: 'history'
	get 'milk_account' => 'milk_productions#today'
	get 'health' => 'cows#health'
	post 'date_account' => 'milk_productions#today'

	#Routes For Goat
	resources :goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :diseases, only: [:new, :create, :edit, :update, :index, :destroy]
	resources :mate_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :parent_goats, only: [:new, :create, :edit, :update, :index, :destroy ]
	get 'goat_status' => 'goats#goat_status'
	post 'goat_status' => 'goats#create_status'
	get 'goat_insurance' => 'goats#goat_insurance'
	post 'goat_insurance' => 'goats#create_insurance'
	get 'farm_status' => 'goats#farm_status'
	get 'find_goat' => 'goats#find_goat'
	get 'goat_diseases' => 'diseases#goat_diseases'
	get 'goat_disease' => 'diseases#goat_disease'
	post 'goat_disease' => 'diseases#create_goat_disease'
	get 'goat_disease/:id/edit', to: 'diseases#edit_goat_disease', as: 'edit_goat_disease'
	post 'update_goat_disease' => 'diseases#update_goat_disease'
	get 'goat_death' => 'diseases#goat_death'
	post 'goat_death' => 'diseases#create_goat_death'
	resources :main_works, only: [:index, :new, :create, :edit, :update, :destroy]
	resources :daily_works, only: [:index, :new, :create, :edit, :update, :destroy]
	get 'good_morning' => 'daily_works#good_morning'
	post 'date_work' => 'daily_works#date_work'
	get 'date_work' => 'daily_works#date_work'
    get 'invoice_year' => 'invoices#invoice_year'
	resources :invoices, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :rack_details, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :batches, only: [:new, :create, :edit, :update, :index, :destroy ]
	resources :goat_weights, only: [:new, :create, :edit, :update, :index, :destroy ]
	get  'batch_weight' => 'goat_weights#batch_weight'
	post  'create_batch_weight' => 'goat_weights#create_batch_weight'
	post  'year_income' => 'home#year_income'
	resources :lands, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crops, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :waters, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :fertilizers, only: [:new, :create, :edit, :update, :index, :show ] 
	get  'land_water' => 'waters#land_water'
	post 'land_water_create' => 'waters#land_water_create'
	get  'land_crop' => 'crops#land_crop'
	post 'land_crop_create' => 'crops#land_crop_create'	
	get 'fodder_management' => 'lands#fodder_management'	
	resources :dry_fodders, only: [:new, :create, :edit, :update, :index, :show ] 
	resources :crop_activities, only: [:new, :create, :edit, :update, :index, :show ] 
	get 'goat_data' => 'goats#get_goat_data'
	get 'get_hole_goat_data' => 'goats#get_hole_goat_data'
	get 'goat_kid_data' => 'goats#goat_kid_data'
	get 'kid_weight_data' => 'goats#kid_weight_data'
	get 'goat_data_batch_wise' => 'batches#goat_data_batch_wise'
	get 'goat_pending_work' => 'pending_works#goat_pending_work'
	get 'daily_pending_work' => 'pending_works#daily_pending_work'

	# Coconut business routes start
	resources :places
	resources :labours
	resources :farmers
	resources :farmer_lands
	resources :vechicles
	resources :purchasers
	resources :purchaser_bills
	resources :farmer_bills
	resources :salarys
	resources :loads
	resources :coconut_invoices
	resources :kopparais
	resources :mattais
	resources :expensess
	get 'find_farmer' => 'farmers#find_farmer'
	post 'tally_farmer' => 'farmers#tally_farmer'
	post 'tally_customer' => 'farmers#tally_customer'
	post 'tally_labour' => 'farmers#tally_labour'
	post 'update_pay' => 'farmers#update_pay'
	
	# Coconut business routes ends
	
	# pdf generation
	get 'download_form' => 'milk_productions#download_form'
	# post 'download_data' => 'milk_productions#download_data'
	post 'download_data', to: 'milk_productions#download_data', as: 'download_data'
	get 'today_farm_update' => 'milk_productions#today_farm_update'
	post 'create_today_farm_status' => 'milk_productions#create_today_farm_status'
	get 'today_work', to: 'milk_productions#generate_pdf', as: 'generate_pdf'
	resources :feed_consumptions
	
end

app/models/cow.rb
class Cow < ApplicationRecord

	has_many :milk_productions, inverse_of: :cow
	has_many :calving_periods, inverse_of: :cow
	has_many :calves, inverse_of: :cow
	has_many :feeds, inverse_of: :cow
	belongs_to :business, inverse_of: :cows

	validates_presence_of :token_no, uniqueness: true
	validates_presence_of :milk_assurance
	validates_presence_of :cow_rate
	validates_presence_of :date_of_purchase
	validates_presence_of :breed_variety
	# validates_presence_of :cow_image
	# validates_presence_of :calving_period
	validates_presence_of :age

	accepts_nested_attributes_for :calving_periods
	accepts_nested_attributes_for :milk_productions
end

app/controllers/cows_controller.rb
class CowsController < BaseController
	def index
    	@cows = Cow.all.order('created_at DESC') 
    	@cows.each do |cow|
    		cow.milk_productions
    	end
  	end 

  	def health
  		@cow_health = Cow.find(params[:cow_id]).calving_periods.order('calve_date ASC')
  	end

	def new
		@cow = Cow.new
		@cow.calving_periods.build
	end

	def create
		@cow = Cow.new(cow_params)
		if @cow.save
	      flash[:success] = 'Your request has been placed. Our agent will contact you shortly!'
	      redirect_to home_url
	    else
	      flash[:danger] = 'Please check the errors.'
	      redirect_to home_url
	    end
	end

	def edit
		@cow = Cow.find(params[:id])
	end

	def update
		@cow = Cow.find(params[:id])
	   if @cow.update_attributes(cow_params)
	      flash[:success] = 'Your request has been placed. Our agent will contact you shortly!'
	      redirect_to home_url
	    else
	      flash[:danger] = 'Please check the errors.'
	      redirect_to home_url
	    end
  	end

  	def cow_health
  		@cow_health = CalvingPeriod.new
  		@cattle_health = CalvingPeriod.all.order('calve_date ASC')
  	end

  	def create_health
  		@cow_health = CalvingPeriod.new(calving_period_params)
		  if @cow_health.save
	      flash[:success] = 'Your request has been placed. Our agent will contact you shortly!'
	      redirect_to home_url
	    else
	      flash[:danger] = 'Please check the errors.'
	      redirect_to home_url
	    end

  	end

	private

	def cow_params
		params.require(:cow).permit(:token_no,:milk_assurance,:cow_rate,:date_of_purchase,:breed_variety,:cow_location,:user_id, :business_id,:age, { calving_periods_attributes: [:cow_status,:calve_date] })
	end

	def calving_period_params
		params.require(:calving_period).permit(:cow_id, :cow_status, :calve_date, :message)
	end 
end

app/helpers/cows_helper.rb
module CowsHelper
end

app/views/cows/_form.html.erb
<%= form_for (@cow) do |f| %>
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block" > 
             <%= image_tag("our_boer.jpg", :class => 'bg-register-image', :size => "450x360"  ) %>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create New Cow</h1>
              </div>
              <form class="user">
                <div class="form-group row">
                  <div class="col-sm-4 mb-3 mb-sm-0">
                    <div class="field">
                      <label for="name" class="label">Token Number :</label>
                    </div>
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= f.text_field :token_no, class: 'form-control form-control-user', id:'token_no', placeholder: 'Enter Token', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Milk Assurance :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.text_field :milk_assurance, class: 'input form-control form-control-user', placeholder: 'Enter Milk ', id: 'milk_assurance', required: true %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Cow Rate :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="field">
                      <%= f.text_field :cow_rate, class: 'input form-control form-control-user', id: 'cow_rate', placeholder: 'Enter Rate', required: true %>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Age :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="field">
                      <%= f.text_field :age, class: 'input form-control form-control-user', placeholder: 'Enter Age',id: 'age', required: true %>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Date Of Purchase :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="field">
                      <div class="field">
                        <%= f.date_field :date_of_purchase, class: 'input input form-control form-control-user',id: 'date_of_purchase', placeholder: 'Enter Date', required: true %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Breed Variety :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="field">
                      <%= f.text_field :breed_variety, class: 'input form-control form-control-user', placeholder: 'Enter Breed Variety',id: 'breed_variety', required: true %>
                    </div>
                  </div>
                </div>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :business_id, value: UserEmployee.find_by(employee_id: current_user).business.id %>
                <%= f.fields_for :calving_periods do |a| %>
                  <div class="form-group row">
                    <div class="col-sm-4">
                      <div class="field">
                        <label for="name" class="label">Cow Status :</label>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="field">
                        <%= a.select :cow_status, CalvingPeriod.cow_statuses.keys, class: 'select form-control form-control-user' %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-4">
                      <div class="field">
                        <label for="name" class="label">Date :</label>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="field">
                        <%= a.date_field :calve_date, class: 'select form-control form-control-user', id: 'date', placeholder: 'Enter Date', required: true %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="field has-text-centered">
                  <button type="submit" class="btn btn-facebook btn-user btn-block">Submit</button>
                </div>
                <hr>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/cows/cow_health.html.erb
<%= form_for :calving_period, :url => cow_health_path(@cow_health) do |f| %>
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block" > 
             <%= image_tag("our_boer.jpg", :class => 'bg-register-image', :size => "450x360"  ) %>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Health</h1>
              </div>
              <form class="user">
                <div class="form-group row">
                  <div class="col-sm-4 mb-3 mb-sm-0">
                    <div class="field">
                      <label for="name" class="label">Cow ID :</label>
                    </div>
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%#= f.text_field :cow_id, class: 'form-control form-control-user', value: 2, required: true, id:'cow_id', placeholder: 'Enter Token', required: true %>
                    <%=f.select :cow_id, options_for_select(Cow.all.collect {|u| [u.token_no, u.id]}), class: 'form-control form-control-user',prompt: "Select Cow", required: 'true' %> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-4">
                    <div class="field">
                      <label for="name" class="label">Cow Status :</label>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <%= f.select :cow_status, CalvingPeriod.cow_statuses.keys, class: 'select form-control form-control-user' %>
                  </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-4">
                      <div class="field">
                        <label for="name" class="label">Date :</label>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="field">
                        <%= f.date_field :calve_date, class: 'select form-control form-control-user', id: 'date', placeholder: 'Enter Date', required: true %>
                      </div>
                    </div>
                  </div>
                <div class="form-group row">
                    <div class="col-sm-4">
                      <div class="field">
                        <label for="name" class="label">Message :</label>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="field">
                        <%= f.text_field :message, class: 'input form-control form-control-user', placeholder: 'Enter Message' %>
                      </div>
                    </div>
                </div>
                <div class="field has-text-centered">
                  <button type="submit" class="btn btn-facebook btn-user btn-block">Submit</button>
                </div>
                <hr>
              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Cattle Health List</h1>
    </div>
    <% if @cattle_health.exists? %>
      <div class="table-responsive">
        <table class="table" width="100%" cellspacing="0">
          <thead class="thead-dark">
          <tr>
            <th> Token No</th>
            <th> Status</th>
            <th> Date </th>
            <th> Message </th>
          </tr>
          </thead>
          <tbody>
          <% @cattle_health.each do |goat_calve| %>
            <tr>
              <td><%= goat_calve.cow.token_no %></td>
              <td><%= goat_calve.cow_status %></td>
              <td><%= goat_calve.calve_date %></td>
              <td><%= goat_calve.message %></td>
            </tr>
            <tr></tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
</div>

app/views/cows/edit.html.erb
<%= render :partial => 'form'  %>

app/views/cows/health.html.erb
<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Cattle Health List</h1>
    </div>
    <% if @cow_health.exists? %>
      <div class="table-responsive">
        <table class="table" width="100%" cellspacing="0">
          <thead class="thead-dark">
          <tr>
            <th> Token No</th>
            <th> Status</th>
            <th> Date </th>
            <th> Message </th>
          </tr>
          </thead>
          <tbody>
          <% @cow_health.each do |cow_calve| %>
            <tr>
              <td><%= cow_calve.cow.token_no %></td>
              <td><%= cow_calve.cow_status %></td>
              <td><%= cow_calve.calve_date %></td>
              <td><%= cow_calve.message %></td>
            </tr>
            <tr></tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
</div>

app/views/cows/index.html.erb
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Cow List</h1>
  </div>
  <% if @cows.exists? %>
    <div class="table-responsive">
      <table class="table" width="100%" cellspacing="0">
        <thead class="thead-dark">
        <tr>
          <th>Token No</th>
          <th>Age</th>
          <th>Cow Status</th>
          <th>ADD Milk</th>
          <th>History</th>
          <th>Health</th>
          <th>Edit</th>
          <th>Feed</th>
        </tr>
        </thead>
        <tbody>
        <% @cows.each do |cow| %>
          <tr>
            <td><%= cow.token_no %></td>
            <td><%= cow.age %></td>
            <td><%= cow.calving_periods.last.cow_status %></td>
            <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-success"> <%= link_to 'ADD Milk', new_milk_production_path(:cow_id => cow.id) %></div></td>
            <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-primary"> <%= link_to 'History',history_path(:cow_id => cow.id) %></div></td>
            <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-primary"> <%= link_to 'Health',health_path(:cow_id => cow.id) %></div></td>
            <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-secondary"><%= link_to 'Edit    ', edit_cow_path(:id => cow.id) %></div></td>
            <td><div class="text-xs font-weight-bold text-uppercase mb-1 btn btn-outline-warning"><%= link_to 'Feed', new_feed_path(:cow_id => cow.id) %></div></td>
          </tr>
          <tr></tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/cows/new.html.erb
<%= render :partial => 'form'  %>